language: ruby
services:
  - mysql
before_script:
  - mysql -e 'create database cat_tree_test;'
  - bundle update
  - "bundle exec ruby spec/prepare.rb"
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
