language: ruby
before_install:
  - gem install bundler
services:
  - mysql
before_script:
  - mysql -e 'create database cat_tree_test;'
  - bundle update
  - "bundle exec ruby spec/prepare.rb"
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
