language: ruby
before_install:
  - gem install bundler
before_script:
  - mysql -e 'create database cat_tree_test;'
  - bundle update
  - "bundle exec ruby spec/prepare.rb"
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
notifications:
  emails:
    - tsukasa.oishi@gmail.com
